* Encoding: UTF-8.
* 08_03_PairedT.

* Dataset: 08_03_PairedT.sav.

EXAMINE VARIABLES=T1 T2 
  /COMPARE VARIABLE
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL
  /MISSING=LISTWISE.

* Add reference line at Y = X.
GRAPH
  /SCATTERPLOT(BIVAR)=T1 WITH T2
  /MISSING=LISTWISE.

T-TEST PAIRS=T1 WITH T2 (PAIRED)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.
