* Encoding: UTF-8.
* 07_02_KMeans.

* Dataset: 07_02_KMeans_begin.sav.

* CREATE THREE CLUSTERS USING PERSONALITY VARIABLES.

QUICK CLUSTER per1 per2 per3 per4 per5
  /MISSING=LISTWISE
  /CRITERIA=CLUSTER(3) MXITER(10) CONVERGE(0)
  /METHOD=KMEANS(NOUPDATE)
  /SAVE CLUSTER
  /PRINT ID(State) INITIAL CLUSTER DISTAN.

* COMPARE CLUSTERS WITH PERSONALITY REGIONS.

CROSSTABS
  /TABLES=per_reg BY QCL_1
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT
  /COUNT ROUND CELL.
