* Encoding: UTF-8.
* 09_04_AutomaticalLM.

* Dataset: 09_04_AutomaticalLM.sav.


* DEFAULT ALM.
*Automatic Linear Modeling. 
LINEAR 
  /FIELDS TARGET=gc08 INPUTS=region gov per_reg per1 per2 per3 per4 per5 gc01 gc02 gc03 gc04 gc05 
    gc06 gc07 gc09 gc10 gc11 gc12 
  /BUILD_OPTIONS OBJECTIVE=STANDARD USE_AUTO_DATA_PREPARATION=TRUE CONFIDENCE_LEVEL=95 
    MODEL_SELECTION=BESTSUBSETS CRITERIA_BEST_SUBSETS=AICC REPLICATE_RESULTS=TRUE SEED=54752075
  /ENSEMBLES COMBINING_RULE_CONTINUOUS=MEAN COMPONENT_MODELS_N=10.

* BOOSTING/ENSEMBLE MODEL.
* https://en.wikipedia.org/wiki/Boosting_(machine_learning).
*Automatic Linear Modeling. 
LINEAR 
  /FIELDS TARGET=gc08 INPUTS=region gov per_reg per1 per2 per3 per4 per5 gc01 gc02 gc03 gc04 gc05 
    gc06 gc07 gc09 gc10 gc11 gc12 
  /BUILD_OPTIONS OBJECTIVE=BOOSTING USE_AUTO_DATA_PREPARATION=TRUE CONFIDENCE_LEVEL=95 
    MODEL_SELECTION=BESTSUBSETS CRITERIA_BEST_SUBSETS=AICC REPLICATE_RESULTS=TRUE SEED=54752075
  /ENSEMBLES COMBINING_RULE_CONTINUOUS=MEAN COMPONENT_MODELS_N=10.

